# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.TextField()),
                ('server_ip', models.GenericIPAddressField()),
                ('login_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('full_name', models.TextField()),
                ('contact', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='serverlogin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.User'),
        ),
    ]
